### ISSUE TITLE
Behavior of the Home tab

### ISSUE THREAD

**Issue by Relwi** [imashnake0/Animite#16]
What behavior will the Home tab have? Will it have an "explore" and/or "trending" tab, or "seasonal" even?

Here are my thoughts for the Home tab (to get started):

- A searchbar on the top to search stuff with a filter, like in [AL-chan](https://github.com/zend10/AL-chan): 
    <details>
    <summary>AL-chan search bar behavior</summary>

    ![image](https://user-images.githubusercontent.com/31081245/163713873-50b87be1-a8ad-4ef6-8c18-8edac5109d23.png)
    ![image](https://user-images.githubusercontent.com/31081245/163713888-b7b278d8-1695-46e8-92e8-b17545f2dab4.png)
    </details>

- Display trending media in horizontal views.
- If the user is logged in, display the name and/or the cover image above the search bar.

These are only some considerations, I think these tasks are essential to start with it:
- [x] Create the GraphQL queries to get trending media.
- [ ] #23.
- [x] Some UX design to have as reference (maybe I'm going to make one).

**Comment by imashnake0** [comment]
These are some great suggestions. Ideally, I want it to look like the main page of [Anilist](https://anilist.co/) the reason I don't have any super complicated requests yet is because I wanted to lay some groundwork first (roughly, according to this [kanban board](https://github.com/users/imashnake0/projects/1)); and also because I should familiarize myself with some of the more complicated aspects of Coroutines (like Flows). I did previously have some other requests that I played around with (the searchbar one for instance) but I digress. I have a rough mockup of what I want the screens to look like in my mind and on paper (yes, I know, *paper*), but nothing concrete yet. We can take this offline if you really want to contribute/discuss more; you can reach me on Discord at imashnake_#0318, or Telegram at @imashnake.

**Comment by Relwi** [comment]
Great! I'm also like you with the groundwork, I need to learn more about Coroutines and some of other aspect of your kanban board, like the dependency injection, Room and Jetpack Compose. 

About the UI, when you make it at Figma, you could share it in an issue or in other site, so I and the new people who come (I hope) can take a look at it to get as reference.

For now I don't have anything to discuss with you, maybe in the future I have some doubts about something with the project and I will send you a message. Also here is my Discord `Relwi#2515` and Telegram `@Relwi` if you want something.

**Comment by imashnake0** [comment]
Sounds good, I will most certainly share mockups if and when I have them ready (I'll likely work on them when I get to "documentation" on the board). Closing this since we can reopen it in the future after laying the said groundwork.
