### ISSUE TITLE
Rendering AniList flavoured Markdown 

### ISSUE THREAD

**Issue by quanta-kt** [imashnake0/Animite#58]
AniList's markdown differs slightly from the standard commonmark markdown.
This requires us to maintain a markdown parser for it separately.

I've been considering forking an existing MD parsing library, the options are:
[commonmark-java](https://github.com/commonmark/commonmark-java)
[JetBrains' MD parser](https://github.com/JetBrains/markdown)

This forum post describes how AL flavoured Markdown differs from CommonMark: https://anilist.co/forum/thread/6125

**Comment by wax911** [comment]
Just to add on to this list, there is also markwon which is a wrapper for [commonmark-java](https://github.com/commonmark/commonmark-java), a couple of the AL clients also use it: https://github.com/noties/Markwon

**Comment by imashnake0** [comment]
Looks like the markdown we fetch can be fetched `asHtml` in most cases. I'm just resorting to [rendering HTML using AndroidView](https://developer.android.com/codelabs/jetpack-compose-migration?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fcompose%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-migration#8) since Compose can't do it rn.
