### ISSUE TITLE
App crashes when airplane mode is enabled

### ISSUE THREAD

**Issue by Zhuinden** [imashnake0/Animite#73]
No stack trace other than this, so it probably crashes in a LazyColumn.

You know what Compose is like 🤷 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.imashnake.animite, PID: 20062
```

I spent 15 minutes looking for the cause, but I'd have to put a log statement after every line, and I don't have the time for that atm.

**Comment by boswelja** [comment]
The cause is there's no network, and Apollo doesn't like that (same with API returning errors)

I thought we had an issue open for the latter, but I guess not. Cc @imashnake0 what are the plans to fix this?

I'd be more concerned about LazyColumn swallowing stacktraces, since it shouldn't be making it that far to start with

**Comment by imashnake0** [comment]
[We need to handle errors](https://github.com/imashnake0/Animite/blob/main/app/src/main/java/com/imashnake/animite/features/home/HomeViewModel.kt#L78).

**Comment by imashnake0** [comment]
Looks like Compose is indeed swallowing the error, I imagine this won't be a problem once we get #67 in. @Iannnr are we handling errors in your PR?

**Comment by Zhuinden** [comment]
@imashnake0 if the crash is coming from Coil, then merging offline db alone won't help you with exceptions coming from AsyncImage, but I am just guessing.

**Comment by imashnake0** [comment]
I'm about 70% sure this happened in the earliest versions that didn't use COIL.
